# ===========================
# Processing report, README and Excel package
# ===========================
# Covers every ionization mode processed in the session plus any differential
# analysis comparisons. Each mode is reported on its own — separate processing
# log, separate PCA, separate methods sentence — because each was processed on
# its own. Only the differential analysis sections combine modes.

# Short, stable prefix for a mode's Excel sheets. With a single mode the sheets
# keep their original unprefixed names.
mode_prefix <- function(label) {
  clean <- gsub("[^A-Za-z0-9]", "", label)
  if (!nzchar(clean)) return("M")
  toupper(substr(clean, 1, 3))
}

mode_sheet_names <- function(modes) {
  prefixed <- length(modes) > 1
  lapply(seq_along(modes), function(i) {
    p <- if (prefixed) paste0(mode_prefix(modes[[i]]$label), "_") else ""
    list(
      original = paste0(p, "data_original"),
      preprocessed = paste0(p, "data_preprocessed"),
      normalized = paste0(p, "data_normalized"),
      normalized_scaled = paste0(p, "data_normalized_scaled"),
      batch_corrected_scaled = paste0(p, "data_batch_corrected_scaled"),
      metadata = paste0(p, "metadata")
    )
  })
}

scale_label_for <- function(scale_norm) {
  switch(scale_norm,
         "ParetoNorm" = "Pareto scaling",
         "AutoNorm" = "Auto scaling (mean-centering and division by standard deviation)",
         "None" = "no scaling",
         scale_norm)
}

norm_label_for <- function(row_norm) {
  switch(row_norm,
         "SumNorm" = "sum normalization",
         "MedianNorm" = "median normalization",
         "None" = "no sample normalization",
         row_norm)
}

# ---------------------------
# Excel README
# ---------------------------
generate_readme <- function(modes, de_runs = list()) {
  rows <- list(data.frame(
    Section = c("ABOUT THIS FILE", "ABOUT THIS FILE"),
    Detail = c(
      paste("Generated by Metabo Tools on", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
      paste0("This file contains all processed versions of your data",
             if (length(modes) > 1) paste0(" for ", length(modes),
                                           " ionization modes, each processed separately") else "",
             ". See each sheet description below to understand which to use for your analysis.")
    ), stringsAsFactors = FALSE))

  sheets <- mode_sheet_names(modes)

  for (i in seq_along(modes)) {
    m <- modes[[i]]
    p <- m$params
    sh <- sheets[[i]]
    mode_tag <- paste0("MODE: ", m$label)

    steps <- c(
      "Step 1: Sample matching — feature matrix columns matched to metadata sample names",
      if (p$do_missing_filter) "Step 2: Missing value filter — features with >50% missing values removed" else "Step 2: Missing value filter — skipped",
      if (p$do_imputation) "Step 3: KNN imputation — remaining missing/zero values imputed" else "Step 3: KNN imputation — skipped",
      if (p$do_iqr_filter) paste0("Step 4: IQR filter — bottom ", p$iqr_threshold, "% lowest variance features removed") else "Step 4: IQR filter — skipped",
      paste("Step 5: Sample normalization —", p$row_norm),
      "Step 6: Log2 transformation",
      if (isTRUE(p$combat_applied)) {
        paste0("Step 7: Batch correction — ComBat (batch variable: ", p$batch_var,
               "; biological variable: ", p$bio_var, ")")
      } else if (isTRUE(p$has_batch)) {
        "Step 7: Batch correction — skipped (batch variable present but ComBat not applied)"
      } else {
        "Step 7: Batch correction — not applicable (no batch variable)"
      },
      paste("Step 8: Scaling —", p$scale_norm)
    )
    rows[[length(rows) + 1]] <- data.frame(
      Section = rep(paste0(mode_tag, " — PIPELINE"), length(steps)),
      Detail = steps, stringsAsFactors = FALSE)

    sheet_rows <- list(
      c(sh$original, "Raw matched matrix with no processing applied. Use this to start the pipeline over from scratch."),
      c(sh$preprocessed, "After missing value filtering and KNN imputation, nothing else applied. Use this to apply your own normalization, transformation and scaling."),
      c(sh$normalized, "After sample normalization and log2 transformation. Use this to apply your own scaling or batch correction method."),
      c(sh$normalized_scaled, paste0(
        "Sample normalized, log2 transformed and scaled (", p$scale_norm, "). ",
        if (isTRUE(p$has_batch)) {
          "Batch effects are still present in this matrix — include the batch column from the metadata sheet as a covariate in your model. "
        } else {
          "No batch variable was supplied for this mode. "
        },
        "Use for statistical modeling."))
    )
    if (isTRUE(p$combat_applied)) {
      sheet_rows[[length(sheet_rows) + 1]] <- c(sh$batch_corrected_scaled, paste0(
        "ComBat batch corrected and scaled (", p$scale_norm, "). ",
        "Use for PCA, clustering and heatmaps. Do not also include batch as a covariate in your model when using this matrix."))
    }
    sheet_rows[[length(sheet_rows) + 1]] <- c(sh$metadata,
      "Full sample metadata for this mode, including the batch column where one was supplied.")

    rows[[length(rows) + 1]] <- data.frame(
      Section = vapply(sheet_rows, function(r) paste0("SHEET: ", r[1]), character(1)),
      Detail = vapply(sheet_rows, function(r) r[2], character(1)),
      stringsAsFactors = FALSE)

    log_rows <- c(
      paste("Features in raw matched matrix:", p$n_original),
      if (p$do_missing_filter) paste("Features after missing value filter:", p$n_after_missing) else "Missing value filter: not applied",
      if (p$do_imputation) paste("Missing/zero values imputed:", p$n_imputed) else "KNN imputation: not applied",
      if (p$do_iqr_filter) paste("Features after IQR filter:", p$n_after_iqr) else "IQR filter: not applied",
      paste("Features in final matrix:", p$n_final),
      paste("Samples matched:", p$n_samples)
    )
    rows[[length(rows) + 1]] <- data.frame(
      Section = rep(paste0(mode_tag, " — PROCESSING LOG"), length(log_rows)),
      Detail = log_rows, stringsAsFactors = FALSE)
  }

  de_rows <- de_readme_rows(de_runs)
  if (!is.null(de_rows)) rows[[length(rows) + 1]] <- de_rows

  do.call(rbind, rows)
}

# ---------------------------
# Excel package
# ---------------------------
build_excel_package <- function(modes, de_runs, file) {
  mat_to_df <- function(mat) tibble::rownames_to_column(as.data.frame(mat), var = "feature")
  sheets <- mode_sheet_names(modes)

  wb <- createWorkbook()
  addWorksheet(wb, "README")
  writeData(wb, "README", generate_readme(modes, de_runs))

  for (i in seq_along(modes)) {
    m <- modes[[i]]
    sh <- sheets[[i]]
    add <- function(name, data) {
      addWorksheet(wb, name)
      writeData(wb, name, data)
    }
    add(sh$original, mat_to_df(m$matched_data$count_matrix))
    add(sh$preprocessed, mat_to_df(m$preprocessed))
    add(sh$normalized, mat_to_df(m$normalized))
    if (!is.null(m$normalized_scaled)) add(sh$normalized_scaled, mat_to_df(m$normalized_scaled))
    if (!is.null(m$batch_corrected_scaled)) {
      add(sh$batch_corrected_scaled, mat_to_df(m$batch_corrected_scaled))
    }
    add(sh$metadata, m$matched_data$full_sample_data)
  }

  for (sheet in de_excel_sheets(de_runs)) {
    addWorksheet(wb, sheet$name)
    writeData(wb, sheet$name, sheet$data)
  }

  headerStyle <- createStyle(textDecoration = "bold", fgFill = "#2980b9",
                             fontColour = "white", wrapText = TRUE)
  addStyle(wb, "README", headerStyle, rows = 1, cols = 1:2, gridExpand = TRUE)
  setColWidths(wb, "README", cols = 1:2, widths = c(35, 90))

  saveWorkbook(wb, file, overwrite = TRUE)
}

# ---------------------------
# HTML report
# ---------------------------
mode_methods_paragraph <- function(mode) {
  p <- mode$params
  sva_version <- as.character(packageVersion("sva"))
  impute_version <- as.character(packageVersion("impute"))

  scaling_sentence <- switch(p$scale_norm,
    "ParetoNorm" = "Data were subsequently Pareto scaled (mean-centered and divided by the square root of the standard deviation of each feature). ",
    "AutoNorm"   = "Data were subsequently auto scaled (mean-centered and divided by the standard deviation of each feature). ",
    "None"       = "",
    "")

  batch_sentence <- if (isTRUE(p$combat_applied)) {
    paste0("Batch effects were removed using the ComBat empirical Bayes method (sva v", sva_version,
           if (!identical(p$bio_var, "None")) {
             paste0(") with biological group (", html_escape(p$bio_var),
                    ") included as a covariate to preserve biological variation during correction (Johnson et al., 2007). ")
           } else ") (Johnson et al., 2007). ")
  } else if (isTRUE(p$has_batch)) {
    paste0("Principal component analysis showed no batch structure requiring correction, so no batch correction was applied; ",
           "batch (", html_escape(p$batch_var), ") was retained in the metadata so it can be included as a covariate in statistical models. ")
  } else {
    "No batch variable was recorded for this mode, so no batch correction was applied. "
  }

  paste0(
    "Metabolomics data processing was performed using Metabo Tools, a web application developed by the ",
    "University of Florida Southeast Center for Integrated Metabolomics (SECIM; ",
    "<a href='https://secim.ufl.edu/'>https://secim.ufl.edu/</a>). ",
    "For the ", html_escape(mode$label), " mode acquisition, raw peak intensity data from ",
    p$n_samples, " samples and ", p$n_original, " features were imported. ",
    if (p$do_missing_filter) paste0("Features with greater than 50% missing or zero values were removed, retaining ",
                                    p$n_after_missing, " features. ") else "",
    if (p$do_imputation) paste0("Remaining missing and zero values (n = ", p$n_imputed,
                                ") were imputed using k-nearest neighbors (KNN, k = 10) as implemented in the ",
                                "Bioconductor impute package (v", impute_version, "). ") else "",
    if (p$do_iqr_filter) paste0("Low-variance features were removed by filtering the bottom ", p$iqr_threshold,
                                "% by interquartile range, retaining ", p$n_after_iqr, " features. ") else "",
    "Samples were normalized by ", norm_label_for(p$row_norm), " followed by log2 transformation. ",
    batch_sentence, scaling_sentence,
    "The final processed matrix contained ", p$n_final, " features across ", p$n_samples, " samples."
  )
}

mode_step_log_html <- function(mode) {
  p <- mode$params
  paste0(
    '<div class="step-log">',
    '<strong>Input:</strong> ', p$n_original, ' features, ', p$n_samples, ' samples<br>',
    if (p$do_missing_filter) paste0('  &#8594; Missing value filter (&gt;50%): <span class="removed">',
                                    p$n_original - p$n_after_missing, ' features removed</span>, <span class="kept">',
                                    p$n_after_missing, ' retained</span><br>') else '  &#8594; Missing value filter: skipped<br>',
    if (p$do_imputation) paste0('  &#8594; KNN imputation: <span class="kept">', p$n_imputed,
                                ' values imputed</span><br>') else '  &#8594; KNN imputation: skipped<br>',
    if (p$do_iqr_filter) paste0('  &#8594; IQR filter (bottom ', p$iqr_threshold, '%): <span class="removed">',
                                p$n_after_missing - p$n_after_iqr, ' features removed</span>, <span class="kept">',
                                p$n_after_iqr, ' retained</span><br>') else '  &#8594; IQR filter: skipped<br>',
    '  &#8594; Sample normalization: ', norm_label_for(p$row_norm), '<br>',
    '  &#8594; Log2 transformation applied<br>',
    '  &#8594; ',
    if (isTRUE(p$combat_applied)) {
      paste0('ComBat batch correction applied (batch: ', html_escape(p$batch_var), ')')
    } else if (isTRUE(p$has_batch)) {
      '<span class="removed">ComBat batch correction skipped</span>'
    } else {
      'ComBat batch correction not applicable (no batch variable)'
    },
    '<br>',
    '  &#8594; Scaling: ', scale_label_for(p$scale_norm), '<br>',
    '<strong>Output:</strong> ', p$n_final, ' features, ', p$n_samples, ' samples',
    '</div>'
  )
}

mode_file_rows <- function(modes) {
  sheets <- mode_sheet_names(modes)
  paste0(vapply(seq_along(modes), function(i) {
    m <- modes[[i]]; sh <- sheets[[i]]; p <- m$params
    rows <- list(
      c(sh$original, "Raw matched matrix, no processing", "Archive. Start the pipeline over from scratch."),
      c(sh$preprocessed, "After missing value filtering and KNN imputation",
        "Apply your own normalization, transformation and scaling."),
      c(sh$normalized, "After sample normalization and log2 transformation",
        "Apply your own scaling or batch correction method."),
      c(paste0(sh$normalized_scaled, ' <span class="tag tag-secondary">modeling</span>'),
        paste0("Normalized, log2 transformed, scaled (", scale_label_for(p$scale_norm), ")"),
        if (isTRUE(p$has_batch)) {
          "Statistical modeling with batch included as a covariate. Batch effects are present in this matrix — they are controlled for in the model, not removed."
        } else {
          "Statistical modeling. No batch variable was supplied for this mode."
        })
    )
    if (isTRUE(p$combat_applied)) {
      rows[[length(rows) + 1]] <- c(
        paste0(sh$batch_corrected_scaled, ' <span class="tag tag-primary">PCA / clustering</span>'),
        paste0("ComBat corrected and scaled (", scale_label_for(p$scale_norm), ")"),
        "PCA, clustering and heatmaps. Do not also include batch as a covariate when using this matrix.")
    }
    rows[[length(rows) + 1]] <- c(sh$metadata, "Sample metadata for this mode",
                                  "Model design, including the batch column where one was supplied.")
    paste0(
      '<tr><td colspan="3" style="background:#eaf4fb;"><strong>', html_escape(m$label), ' mode</strong></td></tr>',
      paste0(vapply(rows, function(r) {
        paste0('<tr><td class="filename">', r[1], '</td><td>', r[2], '</td><td>', r[3], '</td></tr>')
      }, character(1)), collapse = "")
    )
  }, character(1)), collapse = "")
}

generate_html_report <- function(modes, de_runs = list(), output_path) {
  de_runs <- if (is.null(de_runs)) list() else de_runs
  modes <- if (is.null(modes)) list() else modes

  any_combat <- any(vapply(modes, function(m) isTRUE(m$params$combat_applied), logical(1)))
  any_batch <- any(vapply(modes, function(m) isTRUE(m$params$has_batch), logical(1)))

  de_file_rows <- if (length(de_runs) > 0) {
    paste0(
      '<tr><td colspan="3" style="background:#eaf4fb;"><strong>Differential analysis</strong></td></tr>',
      paste0(vapply(seq_along(de_runs), function(i) {
        run <- de_runs[[i]]
        paste0(
          '<tr><td class="filename">', html_escape(de_sheet_name(run, i)),
          ' <span class="tag tag-secondary">results</span></td>',
          '<td>', if (run$mode == "pairwise") "Moderated t-test" else "Moderated F-test",
          ' results for ', html_escape(run$label), '</td>',
          '<td>Per-feature statistics with fold changes, p-values and BH-adjusted FDR. ',
          run$n_sig, ' of ', run$n_features, ' features were significant.</td></tr>')
      }, character(1)), collapse = ""))
  } else ""

  meta_block <- paste0(
    '<div class="meta">',
    '<strong>Generated:</strong> ', format(Sys.time(), "%Y-%m-%d %H:%M:%S"), '<br>',
    '<strong>Ionization modes:</strong> ',
    paste(vapply(modes, function(m) html_escape(m$label), character(1)), collapse = ", "), '<br>',
    paste0(vapply(modes, function(m) {
      paste0('<strong>', html_escape(m$label), ':</strong> ', m$params$n_samples, ' samples, ',
             m$params$n_original, ' features in, ', m$params$n_final, ' out; ',
             if (isTRUE(m$params$combat_applied)) 'ComBat applied' else if (isTRUE(m$params$has_batch)) 'ComBat skipped' else 'no batch variable',
             '; ', scale_label_for(m$params$scale_norm), '<br>')
    }, character(1)), collapse = ""),
    if (length(de_runs) > 0) paste0('<strong>Differential comparisons:</strong> ', length(de_runs), '<br>') else "",
    '</div>')

  methods_block <- paste0(
    '<h2>Methods Paragraph</h2><div class="methods">',
    paste0(vapply(modes, function(m) paste0('<p>', mode_methods_paragraph(m), '</p>'), character(1)), collapse = ""),
    if (any_combat) paste0(
      '<p><strong>Reference:</strong> Johnson WE, Li C, Rabinovic A. ',
      'Adjusting batch effects in microarray expression data using empirical Bayes methods. ',
      '<em>Biostatistics</em>. 2007;8(1):118-127. doi:10.1093/biostatistics/kxj037</p>') else "",
    '<p style="font-size:12px; color:#888; margin-top:10px;">',
    'This paragraph is provided as a draft for your methods section. Please review and adjust as needed for your specific analysis context.',
    '</p></div>')

  processing_block <- paste0(
    '<h2>Processing Steps</h2>',
    paste0(vapply(modes, function(m) {
      paste0('<h3>', html_escape(m$label), ' mode</h3>', mode_step_log_html(m))
    }, character(1)), collapse = ""))

  pca_block <- paste0(
    '<h2>PCA Plots</h2>',
    '<p>PCA is shown per mode, since the modes are separate acquisitions on different intensity scales. Points are colored by biological group and by batch to show whether batch structure is present and, where ComBat was applied, whether it was removed while biological signal was preserved.</p>',
    paste0(vapply(modes, function(m) {
      section <- paste0('<h3>', html_escape(m$label), ' mode</h3>')
      if (!is.null(m$pca_before)) {
        section <- paste0(section, '<h4>Before batch correction</h4>',
                          embed_plotly(create_pca_plots(m$pca_before,
                                                        paste0(m$label, " — before batch correction")), "450px"))
      } else {
        section <- paste0(section, '<p><em>PCA was not run for this mode.</em></p>')
      }
      if (!is.null(m$pca_after)) {
        section <- paste0(section, '<h4>After batch correction and scaling</h4>',
                          embed_plotly(create_pca_plots(m$pca_after,
                                                        paste0(m$label, " — after batch correction and scaling")), "450px"))
      } else if (isTRUE(m$params$has_batch)) {
        section <- paste0(section,
                          '<p><em>ComBat was not applied to this mode, so there is no post-correction PCA.</em></p>')
      }
      section
    }, character(1)), collapse = ""))

  de_block <- if (length(de_runs) > 0) {
    paste0(vapply(seq_along(de_runs), function(i) de_report_section(de_runs[[i]], i), character(1)), collapse = "")
  } else ""

  batch_warning <- if (any_batch) {
    paste0(
      '<div class="warning"><strong>Note on batch correction and statistical modeling:</strong> ',
      'These two approaches are mutually exclusive. If you use a <code>data_batch_corrected_scaled</code> matrix, ',
      'do not include batch as a covariate in your model. If you use <code>data_normalized_scaled</code>, ',
      'include batch as a covariate. Do not do both.</div>')
  } else ""

  html_content <- paste0('
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Metabo Tools Processing Report</title>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <style>
    body { font-family: Arial, sans-serif; max-width: 1100px; margin: 40px auto; padding: 0 20px; color: #333; background: #fff; }
    h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
    h2 { color: #2980b9; margin-top: 40px; }
    h3 { color: #16a085; }
    h4 { color: #555; margin-bottom: 5px; }
    .meta { background: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 30px; font-size: 14px; }
    .methods { background: #eaf4fb; padding: 20px; border-radius: 5px; border-left: 5px solid #3498db; margin-bottom: 30px; line-height: 1.7; }
    .step-log { background: #f8f9fa; padding: 15px; border-radius: 5px; font-family: monospace; font-size: 13px; line-height: 1.8; margin-bottom: 20px; }
    .step-log .removed { color: #e74c3c; }
    .step-log .kept { color: #27ae60; }
    .file-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    .file-table th { background: #2980b9; color: white; padding: 10px 15px; text-align: left; }
    .file-table td { padding: 10px 15px; border-bottom: 1px solid #ddd; vertical-align: top; }
    .file-table .filename { font-family: monospace; font-weight: bold; color: #2c3e50; white-space: nowrap; }
    .tag { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 11px; font-weight: bold; margin-left: 5px; }
    .tag-primary { background: #27ae60; color: white; }
    .tag-secondary { background: #2980b9; color: white; }
    .warning { background: #fef9e7; border-left: 5px solid #f39c12; padding: 15px; border-radius: 5px; margin-top: 20px; }
  </style>
</head>
<body>

<h1>Metabo Tools — Processing Report</h1>
', meta_block, methods_block, processing_block, '

<h2>Output Files Guide</h2>
<p>Your download contains an Excel file with the following sheets.</p>
<table class="file-table">
  <tr><th>Sheet</th><th>Contents</th><th>Use this for</th></tr>
  ', mode_file_rows(modes), de_file_rows, '
</table>
', batch_warning, pca_block, de_block, '

</body>
</html>
')

  writeLines(html_content, output_path)
}
