FROM localhost/batchcorrector:latest
RUN R -e "BiocManager::install('impute', update = FALSE)"
RUN R -e "install.packages('openxlsx', repos='https://cloud.r-project.org')"
RUN R -e "BiocManager::install('limma', update = FALSE)"
RUN R -e "BiocManager::install('ropls', update = FALSE)"
